### ISSUE TITLE
Literature management

### ISSUE THREAD

**Issue by Corrod3** [torbatschow/CSSR_Project#2]
We have to find a strategy to handling literature collaborative. I am normally using citavi for managing literature and handling citations. The advantage is that it easily allows updating and ensures changes are implemented for the whole document. In the case of BibTex it allows exporting the literature list as a .bib, which can than be incorporated in the RMD or LaTex file. One option would be to use the team funtion of citavi and saving it on some form of cloud. However, I am not sure whether you have citavi, whether it works via a cloud and whether this is a convinient way of handling the issue. Another option would be to do it manually, but I think this will get annoying after a certain period. Is there a third option?

**Comment by torbatschow** [comment]
I do not have Citavi (Linux problems...) but we do not have to manage the .bib files manually, as there are a bunch of free .bib editors out there. As the import/export strategy with Citavi caused some troubles, I would suggest using [JabRef](http://www.jabref.org/). Free, open source, works like a charm.
What do you think?

**Comment by torbatschow** [comment]
JabRef it is. Great! :+1:
