### ISSUE TITLE
Research Proposal - Empirical Strategy - Diff-in-diff

### ISSUE THREAD

**Issue by torbatschow** [torbatschow/CSSR_Project#4]
FYI:
I changed the dummy variable names to "dNAME" so a leading "d" for all dummies.

According to your [link](http://stats.stackexchange.com/questions/76058/specifying-a-difference-in-differences-model-with-multiple-time-periods) on multiple time periods in DD, we need 
1. a treatment group dummy (dBW)
2. a year dummy for all years without specifying whether each year belong to the pre or post treatment period (dYEAR)
3. the "interaction term" between treatment group dummy AND a dummy which is 1 after the treatment - basically a dummy which is only 1 for Baden-Württ from 2010 on. (dBAN)
I changed your formula accordingly and left the old ones commented out. Do you agree, @Corrod3 ?

Regarding the common trend assumption:
I agree: we should include an economic indicator (YUR is fine, I think). But shouldn't we also include an indicator that captures somewhat more directly alcohol consumption? If we argue that the yearly beer consumption per capita is not affecting the ARH, this might be as well a good variable to capture non-common trends... What'cha think?

**Comment by Corrod3** [comment]
I will check on Diff-in-Diff in multiple period again as I understood it differently.

Regarding the control variables which ensure the common trend I agree, beer sales is probably a better control than youth unemployment. We will know better once we can eye-ball the data.

**Comment by Corrod3** [comment]
Maybe it helps if we use Marcus and Siedler (2015) as orientation. They do also specify the simple DD model as I did with a post dummy. Ultimately this is the simplest approach. Including the dummy for each time period is as well possible, but it will increase the number of variable which need to be estimated.
It is a further refinement and I would prefer to do so only for the last model.

**Comment by torbatschow** [comment]
I agree on that point, so start off with a dumma splitting pre- and post-treatment, then all-period dummies for the final model. Will change it accordingly.
